export enum Constants {
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  GET_NEWS = 'GET_NEWS',
  LOADING_HEADLINES = 'LOADING_HEADLINES',
  LOADING_HEADLINES_PASSED = 'LOADING_HEADLINES_PASSED',
  LOADING_HEADLINES_FAILED = 'LOADING_HEADLINES_FAILED',
  HEADLINES_LOADED = 'HEADLINES_LOADED',

  LOADING_NEWS = 'LOADING_NEWS',
  LOADING_NEWS_PASSED = 'LOADING_NEWS_PASSED',
  LOADING_NEWS_FAILED = 'LOADING_NEWS_FAILED',
  NEWS_LOADED = 'NEWS_LOADED',
  
  NAV_TO_NEXT_PAGE = 'NAV_TO_NEXT_PAGE',
  NAV_TO_PREV_PAGE = 'NAV_TO_PREV_PAGE',
  SWITCH_COUNTRY = 'SWITCH_COUNTRY',
  SEARCH_NEWS_API = 'SEARCH_NEWS_API',
  SORT_BY = 'SORT_BY',
  SORT_ARTICLES_BY_TIME = 'SORT_ARTICLES_BY_TIME',
  SWITCH_NEWS_READING_MODE = 'SWITCH_NEWS_READING_MODE',
  CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS',

  CHANGE_NEWSSTAND_SIZE= 'CHANGE_NEWSSTAND_SIZE',
  UPDATE_DATE_FILTERS = 'UPDATE_DATE_FILTERS',
  SHOW_ARTICLE = 'SHOW_ARTICLE',
  CLOSE_ARTICLE = 'CLOSE_ARTICLE',
  CAN_LOAD_URL_IN_IFRAME = 'CAN_LOAD_URL_IN_IFRAME',
  CAN_LOAD_URL_IN_IFRAME_RESULTS = 'CAN_LOAD_URL_IN_IFRAME_RESULTS',

  UPDATE_APP_MODE = 'UPDATE_APP_MODE',
}