export enum Constants {
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  GET_NEWS = 'GET_NEWS',
  LOADING_NEWS = 'LOADING_NEWS',
  LOADING_NEWS_PASSED = 'LOADING_NEWS_PASSED',
  LOADING_NEWS_FAILED = 'LOADING_NEWS_FAILED',
  NEWS_LOADED = 'NEWS_LOADED',
  NAV_TO_NEXT_PAGE = 'NAV_TO_NEXT_PAGE',
  NAV_TO_PREV_PAGE = 'NAV_TO_PREV_PAGE',
  SWITCH_COUNTRY = 'SWITCH_COUNTRY',
  SEARCH_NEWS_API = 'SEARCH_NEWS_API',
  SORT_BY = 'SORT_BY',
  SWITCH_NEWS_READING_MODE = 'SWITCH_NEWS_READING_MODE',
}