export enum Constants {
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  GET_NEWS = 'GET_NEWS',

  SWITCH_COUNTRY = 'SWITCH_COUNTRY',
  SEARCH_NEWS_API = 'SEARCH_NEWS_API',
  SORT_BY = 'SORT_BY',
  SORT_ARTICLES_BY_TIME = 'SORT_ARTICLES_BY_TIME',
  SWITCH_NEWS_READING_MODE = 'SWITCH_NEWS_READING_MODE',
  CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS',

  CHANGE_NEWSSTAND_SIZE= 'CHANGE_NEWSSTAND_SIZE',
  UPDATE_DATE_FILTERS = 'UPDATE_DATE_FILTERS',
  SHOW_ARTICLE = 'SHOW_ARTICLE',
  CLOSE_ARTICLE = 'CLOSE_ARTICLE',

  UPDATE_APP_MODE = 'UPDATE_APP_MODE',
  CLOSE_QUICKVIEW = 'CLOSE_QUICKVIEW',

  ADD_TO_POCKET = 'ADD_TO_POCKET',
  GET_POCKET_REQUEST_TOKEN = 'GET_POCKET_REQUEST_TOKEN',
  POCKET_REQUEST_TOKEN_RECVD = 'POCKET_REQUEST_TOKEN_RECVD'
}