{
  query getHeadlines($country: String!, $category: String!) {
    getHeadlines(country: $country, category: $category) {
      title
      author
      description
      url
      urlToImage
      publishedAt
    }
  }
}