export default [
  {
    __typename: "Country",
    code: "au",
    icon: "https://www.countryflags.io/au/flat/64.png",
    id: "au",
    name: "Australia",
  },
  {
    __typename: "Country",
    code: "ca",
    icon: "https://www.countryflags.io/ca/flat/64.png",
    id: "ca",
    name: "Canada",
  },
  {
    __typename: "Country",
    code: "cn",
    icon: "https://www.countryflags.io/cn/flat/64.png",
    id: "cn",
    name: "China",
  },
  {
    __typename: "Country",
    code: "fr",
    icon: "https://www.countryflags.io/fr/flat/64.png",
    id: "fr",
    name: "France",
  },
  {
    __typename: "Country",
    code: "de",
    icon: "https://www.countryflags.io/de/flat/64.png",
    id: "de",
    name: "Germany",
  },
  {
    __typename: "Country",
    code: "in",
    icon: "https://www.countryflags.io/in/flat/64.png",
    id: "in",
    name: "India",
  },
  {
    __typename: "Country",
    code: "jp",
    icon: "https://www.countryflags.io/jp/flat/64.png",
    id: "jp",
    name: "Japan",
  },
  {
    __typename: "Country",
    code: "gb",
    icon: "https://www.countryflags.io/gb/flat/64.png",
    id: "gb",
    name: "United Kingdom",
  },
  {
    __typename: "Country",
    code: "us",
    icon: "https://www.countryflags.io/us/flat/64.png",
    id: "us",
    name: "United States",
  },
];
